name: DiscordStatusPlugin
version: 1.0.0
main: com.example.discordstatus.DiscordStatusPlugin
api-version: '1.21'
author: YourName
description: サーバーの起動・終了時にDiscordチャンネル名を変更するプラグイン

commands:
  discordstatus:
    description: DiscordStatusPluginの設定をリロードします
    usage: /discordstatus reload
    aliases: dsp
    permission: discordstatus.reload

permissions:
  discordstatus.reload:
    description: 設定をリロードする権限
    default: op